language: node_js

node_js:
  - "8"

sudo: true

services:
  - docker

cache:
  directories:
    - "node_modules"

install: npm install

branches:
  only:
  - master

script:
  - npm run build:travis



after_success:
  - docker build -t $DOCKER_PROGRAM .
  - docker login  -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_PROGRAM